export { default as ProductDescription } from './ui/ProductDescription/ProductDescriptions'
export { default as ProductParams } from './ui/ProductParams/ProductParams'
export { default as ProductImages } from './ui/ProductImage/ProductImage'
export { default as PurchaseProduct } from './ui/PurchaseProduct/PurchaseProduct'
export { default as CommentBar } from './ui/CommentBar/CommentBar'
export { default as Thanks } from './ui/Thanks/Thanks'
