export { default as AsideControls } from './ui/AsideControls/Controls'
export { default as SearchProductsForm } from './ui/HeaderSearch/SearchProductsInput'
export { default as SearchHeaderFilters } from './ui/SearchHeaderFilters/Filters'
export { default as SearchPagination } from './ui/SearchPagination/SearchPagination'
export { default as ProductBannerForm } from '../../entities/SearchPage/ui/SearchProductForm/ProductBannerForm'
