export { default as AboutComponent } from './ui/About/About'
export { default as NotFoundComponent } from './ui/NotFound/NotFound'
export { default as AnimatedTheme } from './ui/Layout/AnimatedTheme/AnimatedTheme'
export { default as Header } from './ui/Layout/Header/Header'
export { default as Footer } from './ui/Layout/Footer/Footer'
